GH-1: remove yarn build from pre-push

diff --git a/.githooks/hooks/hook_pre-push b/.githooks/hooks/hook_pre-push
--- a/.githooks/hooks/hook_pre-push
+++ b/.githooks/hooks/hook_pre-push
@@ -16,14 +16,14 @@ NC='\033[0m'
 ##
 # start yarn build and check for approval on to push
 ##
-yarn build
-if [ $? -eq 0 ]; then
-  echo "${GREEN}√${NC} build successful..."
-  echo "${GREEN}-->${NC} Thumbs up! Approving push..."
-  exit 0
-else
-  echo "${RED}Error:${NC} build failed..."
-  echo "${RED}-->${NC} Please check the code and/or build output for errors..."
-  echo "${RED}-->${NC} Rejecting push..."
-  exit 1
-fi
+# yarn build
+# if [ $? -eq 0 ]; then
+#   echo "${GREEN}√${NC} build successful..."
+#   echo "${GREEN}-->${NC} Thumbs up! Approving push..."
+#   exit 0
+# else
+#   echo "${RED}Error:${NC} build failed..."
+#   echo "${RED}-->${NC} Please check the code and/or build output for errors..."
+#   echo "${RED}-->${NC} Rejecting push..."
+#   exit 1
+# fi
